spring:
  boot:
    admin:
      client:
        url: http://localhost:8081  # URL of the Admin Server

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all management endpoints
server:
  port: 8080